### ISSUE TITLE
Import Configurable product with downloadable product as child

### ISSUE THREAD

**Issue by adeshsuryan** [globalera/Magento-Catalog-Import#1]
Hi,
   is any  way   Import Configurable product with downloadable product as child.

**Comment by intelliant01** [comment]
@adeshsuryan Could you please clarify or elaborate your query as I am unable to understand what exactly you are looking for?

**Comment by adeshsuryan** [comment]
Hi intelliant,
                 We can import  2 type pf product ( Configurable and simple ) according  to  current  flow of catalog import  extension  . My  XML having  some download product . Is any way Import Configurable product with downloadable product as child ?

**Comment by intelliant01** [comment]
@adeshsuryan Our apologies that we couldn't revert earlier as the maintainers of this module were not available. Now we have managed to revive this project.
Coming to your query - Your requirement seems a bit confusing as I am unable to visualise any such product.  
By Configurable, we visualise a product with one or more variants and several SKUs that map to multiple simple products. 
By Downloadable, we refer to products that are distributed electronically and may be limited by the number of downloads allowed.
There is nothing stopping us from linking the two but only the specifics of the domain of application shall help us arrive at an answer.

**Comment by intelliant01** [comment]
Closing due to lack of further detail.
